# Generated by Django 5.1.4 on 2026-05-20 10:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_code",
                    models.CharField(editable=False, max_length=12, unique=True),
                ),
                (
                    "raw_message",
                    models.TextField(help_text="Original Customer Message"),
                ),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("send_money", "Send Money"),
                            ("hire_service", "Hire Service"),
                            ("verify_document", "Verify Document"),
                            ("airport_transfer", "Airport Transfer"),
                            ("check_status", "Check Status"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "entities",
                    models.JSONField(
                        default=dict,
                        help_text="AI-extracted entities: amount, recipient, location, urgency, etc.",
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="0 (low) – 100 (high), calculated by risk engine",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                        ],
                        db_index=True,
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_team",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Finance", "Finance"),
                            ("Operations", "Operations"),
                            ("Legal", "Legal"),
                            ("Logistics", "Logistics"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="assistant.task",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Status histories",
                "ordering": ["changed_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                        ],
                        max_length=20,
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="assistant.task",
                    ),
                ),
            ],
            options={
                "ordering": ["channel"],
                "unique_together": {("task", "channel")},
            },
        ),
        migrations.CreateModel(
            name="TaskStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step_order", models.PositiveSmallIntegerField()),
                ("description", models.TextField()),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="assistant.task",
                    ),
                ),
            ],
            options={
                "ordering": ["step_order"],
                "unique_together": {("task", "step_order")},
            },
        ),
    ]
