from django.db import models
import uuid
from django.utils import timezone

class Intent(models.TextChoices):
    SEND_MONEY = "send_money", "Send Money"
    HIRE_SERVICE = "hire_service", "Hire Service"
    VERIFY_DOCUMENT = "verify_document", "Verify Document"
    AIRPORT_TRANSFER = "airport_transfer", "Airport Transfer"
    CHECK_STATUS = "check_status", "Check Status"

class TaskStatus(models.TextChoices):
    PENDING = "Pending", "Pending"
    IN_PROGRESS = "In Progress", "In Progress"
    COMPLETED = "Completed", "Completed"

class AssignedTeam(models.TextChoices):
    FINANCE = "Finance", "Finance"
    OPERATIONS = "Operations", "Operations"
    LEGAL = "Legal", "Legal"
    LOGISTICS = "Logistics", "Logistics"
 
 
class MessageChannel(models.TextChoices):
    WHATSAPP = "whatsapp", "WhatsApp"
    EMAIL = "email", "Email"
    SMS = "sms", "SMS"

INTENT_TEAM_MAP = {
    Intent.SEND_MONEY: AssignedTeam.FINANCE,
    Intent.HIRE_SERVICE: AssignedTeam.OPERATIONS,
    Intent.VERIFY_DOCUMENT: AssignedTeam.LEGAL,
    Intent.AIRPORT_TRANSFER: AssignedTeam.LOGISTICS,
    Intent.CHECK_STATUS: AssignedTeam.OPERATIONS,
}

class Task(models.Model):
    """
    Core task record. Created once per customer request.
    task_code --> human readable refrence e.g (VJX-234)

    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    task_code = models.CharField(max_length=12, unique=True, editable=False)
    raw_message = models.TextField(help_text="Original Customer Message")
    intent = models.CharField(
        max_length=30, choices=Intent.choices, db_index=True
    )
    entities = models.JSONField(
        default=dict,
        help_text="AI-extracted entities: amount, recipient, location, urgency, etc.",
    )
    risk_score = models.PositiveSmallIntegerField(
        default=0,
        help_text="0 (low) – 100 (high), calculated by risk engine",
    )
    status = models.CharField(
        max_length=20, choices=TaskStatus.choices, default=TaskStatus.PENDING, db_index=True
    )
    assigned_team = models.CharField(
        max_length=20, choices=AssignedTeam.choices, blank=True
    )
 
    created_at = models.DateTimeField(default=timezone.now, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "Task"
        verbose_name_plural = "Tasks"

    def save(self, *args, **kwargs):
        # Generate task_code on first save only
        if not self.task_code:
            self.task_code = self._generate_task_code()
        super().save(*args, **kwargs)

    @staticmethod
    def _generate_task_code():
        """Returns a short, uppercase"""
        import random, string
        chars = string.ascii_uppercase + string.digits
        suffix = "".join(random.choices(chars, k=4))
        return f"VNH-{suffix}"
 
    def __str__(self):
        return f"{self.task_code} [{self.intent}] – {self.status}"
    
class TaskStep(models.Model):
    """
    Ordered fulfilment steps for a task, generated by the AI.
    step_order starts at 1. status tracks individual step progress.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name="steps")
    step_order = models.PositiveSmallIntegerField()
    description = models.TextField()
    is_complete = models.BooleanField(default=False)

    class Meta:
        ordering = ["step_order"]
        unique_together = [("task", "step_order")]
 
    def __str__(self):
        return f"{self.task.task_code} – step {self.step_order}"
    
class Message(models.Model):
    """
    One record per channel per task (whatsapp, email, sms).
    All three are created atomically when the task is saved.
    """
 
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name="messages")
    channel = models.CharField(max_length=20, choices=MessageChannel.choices)
    body = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
 
    class Meta:
        ordering = ["channel"]
        unique_together = [("task", "channel")]
 
    def __str__(self):
        return f"{self.task.task_code} [{self.channel}]"

class StatusHistory(models.Model):
    """
    Append-only log of every status change.
    Lets reviewers see the full lifecycle of a task.
    """
 
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name="status_history")
    from_status = models.CharField(max_length=20, blank=True)
    to_status = models.CharField(max_length=20)
    changed_at = models.DateTimeField(default=timezone.now)
    note = models.CharField(max_length=255, blank=True)
 
    class Meta:
        ordering = ["changed_at"]
        verbose_name_plural = "Status histories"
 
    def __str__(self):
        return f"{self.task.task_code}: {self.from_status} → {self.to_status}"
 